version: '3.8'

services:
  # Aplicação Laravel
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: carteira-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - carteira-network
    depends_on:
      - db

  # Servidor Nginx
  nginx:
    image: nginx:alpine
    container_name: carteira-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - carteira-network
    depends_on:
      - app

  # Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: carteira-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - carteira-network

networks:
  carteira-network:
    driver: bridge