version: '3.8'

services:
  # Aplicação Laravel
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: carteira-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=carteira
      - DB_USERNAME=carteira_user
      - DB_PASSWORD=senha_segura
    networks:
      - carteira-network
    depends_on:
      - db

  # Servidor Nginx
  nginx:
    image: nginx:alpine
    container_name: carteira-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - carteira-network
    depends_on:
      - app

  # Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: carteira-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: carteira
      MYSQL_ROOT_PASSWORD: senha_root_segura
      MYSQL_PASSWORD: senha_segura
      MYSQL_USER: carteira_user
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - carteira-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  carteira-network:
    driver: bridge